### PR TITLE
fix access token in query parameter

### LINKED ISSUE #119: Deprecation notice for authentication via URL query parameters
Just had this message from GitHub. Could it have been generated by the GitHub assistant (I don't access GitHub any way that I can think of)?

"_On February 3rd, 2020 at 23:11 (UTC) your personal access token (gas-github_xxxxxxxxx) using Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.106 Safari/537.36 was used as part of a query parameter to access an endpoint through the GitHub API:_

_https://api.github.com/repositories/190063763/branches/v1.9_

_Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated._

_Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all._

_Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information._"

### PR DESCRIPTION
**Pull request by leonhartX**
- fix #119 
- reformat code
- fix regex match failed for github pagination

### CODE REVIEW

File: src/gas-api.js [hunk 1]
```diff
@@ -4,215 +4,229 @@ class Gas {
...
           })
-          .then((response) => {
-            if (!response.startsWith('//OK'))  reject(new Error('get apps script code failed'));
-            //evil eval, but it's simple to get the object since it's not valid json object
-            const codeContent = eval(response.slice(4)).filter((e) => {
-              return typeof(e) === 'object';
-            })[0];
-            resolve({file : codeContent[codeContent.length - 7], content: codeContent[codeContent.length - 10], id : id });
+          .then(resolve)
+          .fail((err) => {
```
Comment (leonhartX) [inline src/gas-api.js]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/leonhartX/gas-github/blob/15f4157afeba0560f3f12968d583a6f4fceda1cf/src/gas-api.js#L161"></span>‘err’ is defined but never used.</td>
    </tr>
  </tbody>
</table>

File: src/gas-api.js [hunk 2]
```diff
@@ -4,215 +4,229 @@ class Gas {
...
+          method: 'POST',
+          crossDomain: true,
+          data: payload,
+          dataType: 'text'
+        })
+        .then((response) => {
+          if (!response.startsWith('//OK')) reject(new Error('Update file failed'));
+          resolve();
+        })
+        .fail((err) => {
```
Comment (leonhartX) [inline src/gas-api.js]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/leonhartX/gas-github/blob/15f4157afeba0560f3f12968d583a6f4fceda1cf/src/gas-api.js#L202"></span>‘err’ is defined but never used.</td>
    </tr>
  </tbody>
</table>

File: src/gas-api.js [hunk 3]
```diff
@@ -4,215 +4,229 @@ class Gas {
...
+          method: 'POST',
+          crossDomain: true,
+          data: payload,
+          dataType: 'text'
+        })
+        .then((response) => {
+          if (!response.startsWith('//OK')) reject(new Error('Delete file failed'));
+          resolve();
+        })
+        .fail((err) => {
```
Comment (leonhartX) [inline src/gas-api.js]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/leonhartX/gas-github/blob/15f4157afeba0560f3f12968d583a6f4fceda1cf/src/gas-api.js#L227"></span>‘err’ is defined but never used.</td>
    </tr>
  </tbody>
</table>

File: src/gas-hub.js [hunk 4]
```diff
@@ -286,31 +300,31 @@ function initPageEvent() {
...
-    const code = {
-      gas: data[0].reduce((hash, elem) => {
-        if (elem && files[elem.file]) hash[files[elem.file].replace(/\.gs$/, context.config.filetype)] = elem.content;
-        return hash;
-      }, {}),
-      scm: data[1].reduce((hash, elem) => {
-        if (elem) {
-          hash[elem.file] = elem.content;
+    .then((data) => {
+      const re = new RegExp(`\\${context.config.filetype}$`);
```
Comment (leonhartX) [inline src/gas-hub.js]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/leonhartX/gas-github/blob/15f4157afeba0560f3f12968d583a6f4fceda1cf/src/gas-hub.js#L304"></span>‘re’ is assigned a value but never used.</td>
    </tr>
  </tbody>
</table>

File: src/gas-hub.js [hunk 5]
```diff
@@ -438,93 +457,101 @@ function updateGist() {
...
-  })
-  .catch(err => {
-    throw new Error('Gist created, but failed to show the new gist.');
-  });
+    .then(() => {
+      $('#new-gist-name').val('');
+      $('#new-gist-public').val('public');
+      showAlert(`Successfully create new gist.`);
+    })
+    .catch(err => {
```
Comment (leonhartX) [inline src/gas-hub.js]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/leonhartX/gas-github/blob/15f4157afeba0560f3f12968d583a6f4fceda1cf/src/gas-hub.js#L552"></span>‘err’ is defined but never used.</td>
    </tr>
  </tbody>
</table>

File: src/scm/bitbucket.js [hunk 6]
```diff
@@ -62,131 +64,136 @@ class Bitbucket {
...
-    .then(() => {
-      showAlert(`Successfully push to ${context.branch} of ${context.repo.fullName}`);
-    })
-    .catch((err) => {
-      showAlert('Failed to push', LEVEL_ERROR);
-    });
+      .then(() => {
+        showAlert(`Successfully push to ${context.branch} of ${context.repo.fullName}`);
+      })
+      .catch((err) => {
```
Comment (leonhartX) [inline src/scm/bitbucket.js]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/leonhartX/gas-github/blob/15f4157afeba0560f3f12968d583a6f4fceda1cf/src/scm/bitbucket.js#L97"></span>‘err’ is defined but never used.</td>
    </tr>
  </tbody>
</table>

File: src/scm/bitbucket.js [hunk 7]
```diff
@@ -62,131 +64,136 @@ class Bitbucket {
...
+          }),
+          this.followPaginate,
+          'bitbucket'
+        );
+      })
+      .then(teams => {
+        this.namespaces = [this.user].concat(teams.map(team => team.username));
+        return this.namespaces;
+      })
+      .catch((err) => {
```
Comment (leonhartX) [inline src/scm/bitbucket.js]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/leonhartX/gas-github/blob/15f4157afeba0560f3f12968d583a6f4fceda1cf/src/scm/bitbucket.js#L171"></span>‘err’ is defined but never used.</td>
    </tr>
  </tbody>
</table>

File: src/scm/bitbucket.js [hunk 8]
```diff
@@ -196,111 +203,126 @@ class Bitbucket {
...
+      .then(repo => {
+        return this.commitFiles(repo, 'master', null, [{
+            name: "README.md",
+            content: "initialed by gas-github"
+          }], null, 'initial commit')
+          .then(() => {
+            return repo;
+          });
+      })
+      .catch((err) => {
```
Comment (leonhartX) [inline src/scm/bitbucket.js]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/leonhartX/gas-github/blob/15f4157afeba0560f3f12968d583a6f4fceda1cf/src/scm/bitbucket.js#L249"></span>‘err’ is defined but never used.</td>
    </tr>
  </tbody>
</table>

File: src/scm/bitbucket.js [hunk 9]
```diff
@@ -196,111 +203,126 @@ class Bitbucket {
...
+        context.branch = branch;
+        Object.assign(context.bindBranch, {
+          [context.id]: branch
+        });
+        chrome.storage.sync.set({
+          bindBranch: context.bindBranch
+        });
+        return branch;
+      })
+      .catch(err => {
```
Comment (leonhartX) [inline src/scm/bitbucket.js]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/leonhartX/gas-github/blob/15f4157afeba0560f3f12968d583a6f4fceda1cf/src/scm/bitbucket.js#L279"></span>‘err’ is defined but never used.</td>
    </tr>
  </tbody>
</table>

File: src/scm/github.js [hunk 10]
```diff
@@ -312,156 +335,169 @@ class Github {
...
+        });
+        if (context.bindBranch[context.id]) {
+          delete context.bindBranch[context.id];
+        }
+        chrome.storage.sync.set({
+          bindRepo: context.bindRepo
+        });
+        return response.full_name;
+      })
+      .catch(err => {
```
Comment (leonhartX) [inline src/scm/github.js]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/leonhartX/gas-github/blob/15f4157afeba0560f3f12968d583a6f4fceda1cf/src/scm/github.js#L376"></span>‘err’ is defined but never used.</td>
    </tr>
  </tbody>
</table>

File: src/scm/github.js [hunk 11]
```diff
@@ -312,156 +335,169 @@ class Github {
...
+        context.branch = gist;
+        Object.assign(context.bindBranch, {
+          [context.id]: gist
+        });
+        chrome.storage.sync.set({
+          bindBranch: context.bindBranch
+        });
+        return response;
+      })
+      .catch(err => {
```
Comment (leonhartX) [inline src/scm/github.js]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/leonhartX/gas-github/blob/15f4157afeba0560f3f12968d583a6f4fceda1cf/src/scm/github.js#L420"></span>‘err’ is defined but never used.</td>
    </tr>
  </tbody>
</table>

File: src/scm/github.js [hunk 12]
```diff
@@ -312,156 +335,169 @@ class Github {
...
+            'Authorization': `token ${this.accessToken}`
+          },
+          method: 'POST',
+          crossDomain: true,
+          dataType: 'json',
+          contentType: 'application/json',
+          data: JSON.stringify(payload)
+        });
+      })
+      .then(response => {
```
Comment (leonhartX) [inline src/scm/github.js]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/leonhartX/gas-github/blob/15f4157afeba0560f3f12968d583a6f4fceda1cf/src/scm/github.js#L464"></span>‘response’ is defined but never used.</td>
    </tr>
  </tbody>
</table>

File: src/scm/gitlab.js [hunk 13]
```diff
@@ -110,70 +118,71 @@ class Gitlab {
...
+        }),
+        this.followPaginate,
+        'gitlab'
+      )
+      .then(groups => {
+        this.namespaces = [this.user].concat(groups.map(group => group.name));
+        this.namesToIds.groups = groups.reduce((obj, item) => (obj[item.name] = item.id, obj), {});
+        return this.namespaces;
+      })
+      .catch((err) => {
```
Comment (leonhartX) [inline src/scm/gitlab.js]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/leonhartX/gas-github/blob/15f4157afeba0560f3f12968d583a6f4fceda1cf/src/scm/gitlab.js#L162"></span>‘err’ is defined but never used.</td>
    </tr>
  </tbody>
</table>

File: src/scm/gitlab.js [hunk 14]
```diff
@@ -236,23 +252,27 @@ class Gitlab {
...
           .then(resolve)
           .fail(reject);
       })
-        .then(response => {
-          context.branch = branch;
-          Object.assign(context.bindBranch, { [context.id] : branch });
-          chrome.storage.sync.set({ bindBranch: context.bindBranch });
-          return branch;
-        })
+      .then(response => {
```
Comment (leonhartX) [inline src/scm/gitlab.js]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/leonhartX/gas-github/blob/15f4157afeba0560f3f12968d583a6f4fceda1cf/src/scm/gitlab.js#L266"></span>‘response’ is defined but never used.</td>
    </tr>
  </tbody>
</table>

File: src/util.js [hunk 15]
```diff
@@ -18,4 +18,18 @@ function createSCM(item) {
     default:
       return new Github(item.baseUrl, item.user, item.token);
   }
+}
+
+function getGitHubJSON(url, accessToken, data) {
```
Comment (leonhartX) [inline src/util.js]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/leonhartX/gas-github/blob/15f4157afeba0560f3f12968d583a6f4fceda1cf/src/util.js#L23"></span>‘getGitHubJSON’ is defined but never used.</td>
    </tr>
  </tbody>
</table>

**Comment by leonhartX** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR, try to keep changes smaller if you can</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>
