### PR TITLE
use github api to get userinfo

### LINKED ISSUE #43: Login github use email cause wrong username
Now the username is just get from input, since email is not a valid username(which used as a repo prefix), should use github api to retrieve the login username

### PR DESCRIPTION
**Pull request by leonhartX**
call github's /user api to get the login username(work for email login)
fix #43

### CODE REVIEW

File: options/options.js [hunk 1]
```diff
@@ -1,26 +1,26 @@
...
 
 $(() => {
-  $('.message a').click(function(e){
+  $('.message a').click(e => {
     $('.error').hide();
     $('.login-container').animate({height: 'hide', opacity: 'hide'}, 'slow');
     $(`.${e.target.name}-login-container`).animate({height: 'show', opacity: 'show'}, 'slow');
   });
-  $('#login').click((e) => {
+  $('#login').click(e => {
```
Comment (leonhartX) [inline options/options.js]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/leonhartX/gas-github/blob/3bad4bc025cc43cc251f17b68f22b94ac54ac1f0/options/options.js#L9"></span>‘e’ is defined but never used.</td>
    </tr>
  </tbody>
</table>

File: options/options.js [hunk 2]
```diff
@@ -1,26 +1,26 @@
...
     addCred(getGithubParam());
   });
-  $('#ghe-login').click((e) => {
+  $('#ghe-login').click(e => {
```
Comment (leonhartX) [inline options/options.js]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/leonhartX/gas-github/blob/3bad4bc025cc43cc251f17b68f22b94ac54ac1f0/options/options.js#L12"></span>‘e’ is defined but never used.</td>
    </tr>
  </tbody>
</table>

File: options/options.js [hunk 3]
```diff
@@ -1,26 +1,26 @@
...
     addCred(getGHEParam());
   });
-  $('#bitbucket-login').click((e) => {
+  $('#bitbucket-login').click(e => {
```
Comment (leonhartX) [inline options/options.js]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/leonhartX/gas-github/blob/3bad4bc025cc43cc251f17b68f22b94ac54ac1f0/options/options.js#L15"></span>‘e’ is defined but never used.</td>
    </tr>
  </tbody>
</table>

File: options/options.js [hunk 4]
```diff
@@ -1,26 +1,26 @@
...
     addCred(getBitbucketParam());
   });
-  $('#logout').click((e) => {
+  $('#logout').click(e => {
```
Comment (leonhartX) [inline options/options.js]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/leonhartX/gas-github/blob/3bad4bc025cc43cc251f17b68f22b94ac54ac1f0/options/options.js#L18"></span>‘e’ is defined but never used.</td>
    </tr>
  </tbody>
</table>

File: options/options.js [hunk 5]
```diff
@@ -49,7 +49,7 @@ $(() => {
     $('#login-user').text(`${user}${domain}`).attr('href', userLink);
     $('#token').attr('href', tokenLink);
   })
-  .catch((err) => {
+  .catch(err => {
```
Comment (leonhartX) [inline options/options.js]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/leonhartX/gas-github/blob/3bad4bc025cc43cc251f17b68f22b94ac54ac1f0/options/options.js#L52"></span>‘err’ is defined but never used.</td>
    </tr>
  </tbody>
</table>

**Comment by leonhartX** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">manifest is not changed, forget to bump version?</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>
